name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          go build -C src -o ../compiler
          ./compiler -path references.bib > /dev/null
